import { detailsImages } from "@/lib/imagery";

export const aboutValues = [
  { icon: "leaf", vi: { title: "Tự nhiên là điểm bắt đầu", body: "Ưu tiên nguồn sợi thực vật, tìm khả năng tạo giá trị từ lá dứa sau thu hoạch và cuống sen. Mỗi lựa chọn vật liệu cần đi cùng thử nghiệm thực tế." }, en: { title: "Nature is the starting point", body: "Explore botanical fibres and new value for post-harvest pineapple leaves and lotus stems. Each material choice must be supported by practical trials." } },
  { icon: "fingerprint", vi: { title: "Bản sắc nằm trong sợi", body: "Kết nối nguồn nguyên liệu Việt với kỹ nghệ rút tơ sen và ngôn ngữ thiết kế đương đại. Trân trọng công sức của người làm nghề." }, en: { title: "Identity lives in the fibre", body: "Connect Vietnamese botanicals and lotus silk craft with contemporary design. Respect the time and skill of the people behind each thread." } },
  { icon: "scan", vi: { title: "Minh bạch để tin tưởng", body: "Hướng đến hồ sơ vật liệu có thể theo dấu. Phân biệt rõ thông tin đã xác nhận, mục tiêu phát triển và hình ảnh tham khảo trong đề án." }, en: { title: "Trust starts with transparency", body: "Work towards traceable material profiles. Clearly distinguish confirmed information, development goals and project reference images." } },
  { icon: "users", vi: { title: "Giá trị được sẻ chia", body: "Hình dung một chuỗi kết nối nông hộ, hợp tác xã, người làm nghề và nhà thiết kế. Vật liệu chỉ thực sự có ý nghĩa khi tìm được ứng dụng phù hợp." }, en: { title: "Value is shared", body: "Imagine a chain connecting growers, cooperatives, makers and designers. Materials find their meaning through thoughtful, practical applications." } },
] as const;

export const aboutMaterials = [
  { id: "pinefiber", name: "PineFiber", image: detailsImages.pinefiber, vi: { origin: "LÁ DỨA SAU THU HOẠCH", title: "Nét mộc làm nền tảng.", text: "Hướng vật liệu chủ lực từ sợi lá dứa, tập trung vào cấu trúc vải ứng dụng và khả năng phát triển sản xuất. Được hình dung cho trang phục thường ngày và phụ kiện.", composition: "Sợi lá dứa", use: "Áo sơ mi · Túi · Mũ · Ví" }, en: { origin: "POST-HARVEST PINEAPPLE LEAVES", title: "Earthy by nature.", text: "The core pineapple leaf fibre direction, focused on practical woven structures and developing production capacity. Intended for everyday apparel and accessories.", composition: "Pineapple leaf fibre", use: "Shirts · Bags · Hats · Wallets" } },
  { id: "blend", name: "SenPine Blend", image: detailsImages.blend, vi: { origin: "LÁ DỨA × TƠ SEN", title: "Hai nguồn sợi cùng đi tiếp.", text: "Nghiên cứu phối trộn sợi lá dứa và tơ sen để tìm sự cân bằng giữa nét mộc, cảm giác chạm và độ rũ. Ảnh minh họa nguồn sợi, chưa phải mẫu vải Blend hoàn thiện.", composition: "95% lá dứa / 5% tơ sen — đề xuất", use: "Váy · Áo sơ mi · Khăn choàng" }, en: { origin: "PINEAPPLE × LOTUS SILK", title: "Two fibres, moving forward.", text: "Explore a pineapple and lotus blend to balance texture, hand-feel and drape. The image illustrates fibre sources rather than a finished Blend fabric sample.", composition: "95% pineapple / 5% lotus — proposed", use: "Dresses · Shirts · Scarves" } },
  { id: "sensilk", name: "SenSilk", image: detailsImages.sensilk, vi: { origin: "TƠ TỪ CUỐNG SEN", title: "Dành chỗ cho sự tỉ mỉ.", text: "Dòng vật liệu giới hạn gắn với kỹ nghệ rút tơ sen thủ công. Định hướng cho những thiết kế trân trọng giá trị của thời gian và công sức làm nghề. Ảnh vải thêu sen là hình tham khảo.", composition: "Tơ sen thủ công", use: "Khăn · Trang phục đặc biệt · Dòng giới hạn" }, en: { origin: "LOTUS STEM SILK", title: "Make room for the details.", text: "A limited material direction rooted in hand-extracted lotus silk. Intended for designs that honour time and craft. The lotus embroidery image is a project reference.", composition: "Hand-extracted lotus silk", use: "Scarves · Occasion wear · Limited editions" } },
] as const;

export const aboutProcess = [
  { image: detailsImages.harvest, vi: { title: "Từ vùng nguyên liệu", text: "Tìm nguồn lá dứa sau thu hoạch và cuống sen phù hợp. Kế hoạch bắt đầu bằng việc hiểu vùng trồng, mùa vụ, chất lượng và khả năng liên kết với nông hộ, hợp tác xã.", result: "Đầu ra định hướng: nguồn nguyên liệu có hồ sơ." }, en: { title: "Begin at the source", text: "Identify suitable post-harvest pineapple leaves and lotus stems. Understand growing regions, seasonality, quality and opportunities to work with growers and cooperatives.", result: "Intended output: documented botanical sources." } },
  { image: detailsImages.extraction, vi: { title: "Tách xơ, phát triển sợi", text: "Đề xuất xử lý lá dứa, rút tơ sen, làm sạch và phân loại xơ. Kéo sợi và phối trộn cần được thử nghiệm để xác nhận độ ổn định trước bước dệt vải.", result: "Đầu ra định hướng: sợi và phương án phối trộn thử nghiệm." }, en: { title: "Extract fibre, develop yarn", text: "Explore pineapple fibre extraction, lotus silk drawing, cleaning and sorting. Spinning and blending require testing to establish consistency before weaving.", result: "Intended output: trial yarns and blend formulations." } },
  { image: detailsImages.pinefiber, vi: { title: "Dệt, hoàn thiện, kiểm tra", text: "Phát triển mẫu vải, lựa chọn cấu trúc dệt và phương án hoàn thiện. Cảm giác chạm, độ rũ, độ bền và thành phần phải được đánh giá bằng mẫu và dữ liệu kiểm nghiệm.", result: "Đầu ra định hướng: mẫu vải có thông số được xác nhận." }, en: { title: "Weave, finish, evaluate", text: "Develop swatches, weave structures and finishing options. Hand-feel, drape, strength and composition need to be assessed through physical samples and test data.", result: "Intended output: swatches with validated specifications." } },
  { image: detailsImages.scarf, vi: { title: "Thiết kế, trải nghiệm, theo dấu", text: "Đưa vật liệu vào các nhóm sản phẩm minh họa, thu nhận phản hồi và phát triển hồ sơ truy xuất. Website kết nối câu chuyện nguồn sợi, hồ sơ vật liệu và trải nghiệm thiết kế.", result: "Đầu ra định hướng: thiết kế ứng dụng và hộ chiếu vật liệu." }, en: { title: "Design, experience, trace", text: "Explore product concepts, gather feedback and develop traceability profiles. The website connects fibre origins, material information and the design experience.", result: "Intended output: design applications and material passports." } },
] as const;

export const aboutRoadmap = [
  { months: "01–06", vi: { title: "Chuẩn bị đầu tư", text: "Nghiên cứu tính khả thi, thị trường, nguyên liệu và công nghệ. Xây dựng kế hoạch kinh doanh, sản xuất và tài chính.", tasks: ["Nghiên cứu nhu cầu và nguồn sợi", "Phát triển kế hoạch sản phẩm", "Chuẩn bị vốn, pháp lý và đối tác"] }, en: { title: "Lay the foundations", text: "Study feasibility, the market, botanicals and technology. Establish business, production and financial plans.", tasks: ["Research demand and fibre sources", "Develop the product plan", "Prepare funding, legal setup and partnerships"] } },
  { months: "07–14", vi: { title: "Chuẩn bị sản xuất", text: "Hình dung cơ sở sản xuất, thiết bị và đội ngũ. Chạy thử quy trình và hoàn thiện các mẫu vật liệu, mẫu thiết kế.", tasks: ["Chuẩn bị nhà xưởng và thiết bị", "Tuyển dụng, đào tạo đội ngũ", "Thử nghiệm chất lượng và mẫu B2C"] }, en: { title: "Prepare for production", text: "Plan facilities, equipment and the team. Trial the process and develop material and design samples.", tasks: ["Prepare facilities and equipment", "Recruit and train the team", "Trial quality and B2C samples"] } },
  { months: "15–17", vi: { title: "Ra mắt thị trường", text: "Theo kế hoạch, giới thiệu thương hiệu và bắt đầu thử nghiệm các kênh bán hàng cho đối tác B2B và người dùng B2C.", tasks: ["Giới thiệu thương hiệu", "Thử nghiệm kênh tiếp cận khách hàng", "Bắt đầu cung cấp sản phẩm theo kế hoạch"] }, en: { title: "Introduce the brand", text: "The plan proposes a brand launch and initial market channels for B2B partners and B2C users.", tasks: ["Introduce the brand", "Trial customer acquisition channels", "Begin the proposed commercial offering"] } },
  { months: "18–24", vi: { title: "Ổn định và tăng trưởng", text: "Chuẩn hóa quy trình, chất lượng và nguồn nguyên liệu. Mở rộng tệp khách hàng từ phản hồi và dữ liệu vận hành.", tasks: ["Ổn định nguồn nguyên liệu", "Chuẩn hóa sản xuất và chất lượng", "Phát triển khách hàng B2B, B2C"] }, en: { title: "Stabilise and grow", text: "Standardise quality, production and sourcing. Develop the customer base through feedback and operational data.", tasks: ["Stabilise material sourcing", "Standardise production and quality", "Develop B2B and B2C relationships"] } },
  { months: "25–30", vi: { title: "Hướng đến hòa vốn", text: "Mục tiêu tối ưu sản lượng, chi phí và dòng sản phẩm. Cân bằng tài chính là một mục tiêu trong đề án, cần được đánh giá bằng kết quả thực tế.", tasks: ["Tối ưu chi phí và sản lượng", "Quản lý nhân sự, tồn kho", "Ưu tiên sản phẩm phù hợp thị trường"] }, en: { title: "Work towards break-even", text: "Aim to optimise output, costs and product focus. Financial balance is a project goal that must be assessed against actual results.", tasks: ["Optimise output and costs", "Manage staffing and inventory", "Focus on market-appropriate products"] } },
  { months: "31–42", vi: { title: "Mở cơ hội quốc tế", text: "Nghiên cứu thị trường nước ngoài, tìm đối tác và chuẩn bị yêu cầu chất lượng, hồ sơ và logistics phù hợp.", tasks: ["Nghiên cứu thị trường và đối tác", "Chuẩn bị hồ sơ, tiêu chuẩn cần thiết", "Phát triển phương án logistics"] }, en: { title: "Explore beyond Vietnam", text: "Research international markets and partners, then prepare the relevant quality, documentation and logistics requirements.", tasks: ["Research markets and partnerships", "Prepare necessary documentation and standards", "Develop a logistics plan"] } },
] as const;

// Design descriptions deliberately describe concepts rather than untested performance claims.
export const aboutProductNotes = [
  { vi: "Phom áo thư thái, sắc ivory và cấu trúc dệt mộc. Một hướng ứng dụng PineFiber cho tủ đồ hằng ngày.", en: "A relaxed silhouette, ivory tones and a visible weave. A PineFiber direction for the everyday wardrobe." },
  { vi: "Đường dáng dài và sắc sage dịu. Concept khai thác hướng độ rũ của SenPine Blend trong thiết kế trang phục.", en: "An elongated silhouette in gentle sage. A concept exploring the intended drape of SenPine Blend." },
  { vi: "Một lớp vải nhẹ để khoác và mang theo. Thiết kế minh họa sự gặp gỡ của chất liệu, nếp gấp và chuyển động.", en: "A light layer to wear and carry. A design study in material, folds and movement." },
  { vi: "Phom tote gọn, quai cầm rõ nét và màu sợi tự nhiên. Một cách đưa hướng vải PineFiber vào phụ kiện thường ngày.", en: "A simple tote, defined handles and natural fibre colours. An everyday accessory direction for PineFiber." },
  { vi: "Vành mũ mềm và sắc xanh mộc. Hướng thiết kế phụ kiện tối giản để đồng hành trong những chuyến đi.", en: "A soft brim and botanical green. A minimal accessory concept for everyday outings." },
  { vi: "Một thiết kế nhỏ với các đường may và ngăn chứa có chủ đích. Gợi ý ứng dụng cấu trúc dệt mịn của PineFiber.", en: "A compact design with considered seams and compartments. A proposed use for a finer PineFiber weave." },
] as const;
