"use client";

import Link from "next/link";
import { useState } from "react";
import { ArrowUpRight, Check } from "lucide-react";
import { materials } from "@/lib/content";

export function BusinessForm({ kind }: { kind: "sample" | "quote" | "contact" }) {
  const [submitted, setSubmitted] = useState(false);
  if (submitted) return <div className="form-complete" role="status"><Check size={47} strokeWidth={1.5} /><h2>Đã hoàn tất bản demo.</h2><p>Biểu mẫu đã được kiểm tra trong trình duyệt. Thông tin chưa được gửi hay lưu; hiện không có yêu cầu thực tế được tạo.</p><Link className="button button-dark" href="/">Về trang chủ <ArrowUpRight size={20} /></Link></div>;
  return <form className="business-form" onSubmit={(event) => { event.preventDefault(); setSubmitted(true); }}><p className="page-note">Đây là biểu mẫu trải nghiệm. SenPine chưa tiếp nhận yêu cầu qua website này; dữ liệu bạn nhập không được gửi đi.</p><div className="form-row"><label className="form-label">Họ và tên *<input name="name" autoComplete="name" maxLength={100} required placeholder="Tên của bạn" /></label><label className="form-label">Email *<input name="email" type="email" autoComplete="email" maxLength={150} required placeholder="you@example.com" /></label></div>{kind !== "contact" && <div className="form-row"><label className="form-label">Thương hiệu / tổ chức *<input name="organization" autoComplete="organization" maxLength={150} required placeholder="Tên thương hiệu hoặc tổ chức" /></label><label className="form-label">Vật liệu quan tâm<select name="material"><option value="all">Chưa xác định</option>{materials.map((material) => <option key={material.id} value={material.id}>{material.name}</option>)}</select></label></div>}{kind === "sample" && <div className="form-row"><label className="form-label">Ứng dụng dự kiến<select name="application"><option>Thời trang</option><option>Phụ kiện</option><option>Nội thất</option><option>Nghiên cứu khác</option></select></label><label className="form-label">Số bộ mẫu dự kiến<input name="quantity" type="number" min={1} max={20} defaultValue={1} required /></label></div>}{kind === "quote" && <div className="form-row"><label className="form-label">Khối lượng dự kiến<input name="amount" maxLength={100} placeholder="Ví dụ: 50 mét" /></label><label className="form-label">Thời gian mong muốn<input name="timeline" maxLength={100} placeholder="Ví dụ: quý IV/2027" /></label></div>}<label className="form-label">{kind === "contact" ? "Nội dung liên hệ *" : "Mô tả nhu cầu *"}<textarea name="message" rows={5} minLength={10} maxLength={1500} required placeholder={kind === "sample" ? "Bạn muốn dùng mẫu vải cho ứng dụng nào?" : "Chia sẻ ý tưởng hoặc câu hỏi của bạn…"} /></label><button className="button button-dark" type="submit">Hoàn tất trải nghiệm demo <ArrowUpRight size={20} /></button></form>;
}
