import { chromium } from "@playwright/test";
import assert from "node:assert/strict";
import { mkdir } from "node:fs/promises";

const output = ".artifacts";
const base = process.env.SENPINE_URL || "http://localhost:3000";
await mkdir(output, { recursive: true });
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || "C:/Program Files/Google/Chrome/Application/chrome.exe", headless: true });
const errors = [];
async function openHome(page) {
  await page.goto(base, { waitUntil: "networkidle" });
  await page.locator(".botanical-intro").waitFor({ state: "detached" });
}
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
  page.on("pageerror", (error) => errors.push(error.message));
  await openHome(page);
  await page.locator(".botanical-intro").waitFor({ state: "detached" });
  await page.locator(".hero h1").waitFor();
  await page.waitForFunction(() => [...document.querySelectorAll(".hero-copy > *")].every((element) => getComputedStyle(element).opacity === "1"));
  assert.equal(await page.locator(".hero-scene").count(), 3);
  await page.screenshot({ path: `${output}/desktop-hero.png` });
  const firstScene = await page.locator(".hero-scene.is-active img").getAttribute("src");
  await page.waitForFunction((src) => document.querySelector(".hero-scene.is-active img")?.getAttribute("src") !== src, firstScene, { timeout: 9000 });
  await page.locator(".hero-scene-buttons button").first().click();
  await page.locator("#origins").scrollIntoViewIfNeeded();
  await page.waitForFunction(() => [...document.querySelectorAll("#origins .origin-panel")].every((element) => getComputedStyle(element).clipPath === "none"));
  await page.screenshot({ path: `${output}/desktop-origins.png` });
  await page.locator("#journey").scrollIntoViewIfNeeded();
  assert.equal(await page.locator(".journey-stage-list > li").count(), 7);
  await page.waitForFunction(() => document.querySelector(".journey-figure-slide.is-active img")?.complete);
  await page.locator(".journey-stage-button").nth(3).click();
  assert.equal(await page.locator(".journey-stage-button").nth(3).getAttribute("aria-expanded"), "true");
  assert.ok((await page.locator(".journey-figure-slide.is-active img").getAttribute("src")).includes("spinning-machine.webp"));
  await page.locator(".journey-stage-button").first().click();
  await page.screenshot({ path: `${output}/desktop-journey.png` });
  await page.locator("#materials").scrollIntoViewIfNeeded();
  await page.waitForFunction(() => [...document.querySelectorAll(".material-item")].every((element) => getComputedStyle(element).opacity === "1"));
  await page.screenshot({ path: `${output}/desktop-materials.png` });
  await page.getByRole("button", { name: "Khám phá PineFiber", exact: true }).click();
  await page.getByRole("dialog").waitFor();
  assert.ok((await page.getByRole("dialog").innerText()).includes("500.000"));
  await page.getByRole("button", { name: "Đóng cửa sổ" }).click();
  await page.getByRole("button", { name: "Lưu Áo sơ mi tự nhiên", exact: true }).click();
  await page.getByRole("button", { name: "Sản phẩm đã lưu (1)", exact: true }).click();
  assert.ok((await page.getByRole("dialog").innerText()).includes("Áo sơ mi tự nhiên"));
  await page.keyboard.press("Escape");
  await page.getByRole("button", { name: "Tìm sản phẩm", exact: true }).click();
  await page.getByRole("searchbox").fill("khăn");
  assert.equal(await page.locator(".search-results > button").count(), 1);
  await page.locator(".search-results > button").click();
  assert.ok((await page.getByRole("dialog").innerText()).includes("Khăn choàng"));
  await page.screenshot({ path: `${output}/desktop-product.png` });
  await page.keyboard.press("Escape");
  await page.getByRole("button", { name: "Mở hộ chiếu vật liệu mẫu" }).click();
  await page.getByLabel("Chọn hồ sơ minh họa").selectOption("SP-SB-001");
  assert.ok((await page.locator(".trace-result").innerText()).includes("95%"));
  await page.keyboard.press("Escape");
  assert.ok(await page.getByRole("link", { name: "Tìm hiểu hợp tác" }).count());
  await page.locator(".product-rail").scrollIntoViewIfNeeded();
  await page.getByRole("button", { name: "Tất cả", exact: true }).focus();
  const railBox = await page.locator(".product-rail").boundingBox();
  await page.mouse.move(railBox.x + 30, railBox.y + 70);
  const resumedScroll = await page.locator(".product-rail").evaluate((element) => element.scrollLeft);
  await page.waitForFunction((previous) => document.querySelector(".product-rail").scrollLeft !== previous, resumedScroll, { timeout: 8000 });
  const hoveredScroll = await page.locator(".product-rail").evaluate((element) => element.scrollLeft);
  await page.waitForTimeout(2900);
  assert.ok(await page.locator(".product-rail").evaluate((element) => element.scrollLeft) > hoveredScroll, "Collection should keep flowing while hovered");
  await page.mouse.move(5, 5);
  await page.waitForFunction(() => document.querySelector(".product-rail").scrollLeft > 10, null, { timeout: 6000 });
  for (const width of [360, 390, 768]) {
    await page.setViewportSize({ width, height: 844 });
    await openHome(page);
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), `Page overflow at ${width}px`);
    await page.getByRole("button", { name: "Mở menu", exact: true }).click();
    await page.getByRole("navigation", { name: "Điều hướng trên điện thoại" }).getByRole("link", { name: "Bộ sưu tập" }).click();
    await page.waitForURL("**/collection");
    assert.equal(await page.locator(".collection-grid .editorial-card").count(), 6);
    await openHome(page);
    await page.locator(".product-rail").scrollIntoViewIfNeeded();
    await page.screenshot({ path: `${output}/mobile-collection-${width}.png` });
    const before = await page.locator(".product-rail").evaluate((element) => element.scrollLeft);
    await page.getByRole("button", { name: "Xem thêm sản phẩm", exact: true }).click();
    await page.waitForFunction((previous) => document.querySelector(".product-rail").scrollLeft > previous, before);
    if (width === 390) {
      await page.getByRole("button", { name: "Xem Váy dáng dài", exact: true }).click();
      await page.screenshot({ path: `${output}/mobile-product.png` });
      await page.keyboard.press("Escape");
      await openHome(page);
      await page.waitForFunction(() => [...document.querySelectorAll(".hero-copy > *")].every((element) => getComputedStyle(element).opacity === "1"));
      await page.screenshot({ path: `${output}/mobile-hero.png` });
      const secondOrigin = page.locator(".origin-panel.pineapple");
      assert.notEqual(await secondOrigin.evaluate((element) => getComputedStyle(element).clipPath), "none", "The lower origin panel should wait for the viewport");
      await secondOrigin.scrollIntoViewIfNeeded();
      await page.waitForFunction(() => getComputedStyle(document.querySelector(".origin-panel.pineapple")).clipPath === "none");
      const lastStage = page.locator(".journey-stage-list li").last();
      assert.ok(Number(await lastStage.evaluate((element) => getComputedStyle(element).opacity)) < 1, "The last journey step should wait for the viewport");
      await lastStage.scrollIntoViewIfNeeded();
      await page.waitForFunction(() => getComputedStyle(document.querySelector(".journey-stage-list li:last-child")).opacity === "1");
      const lastMaterial = page.locator(".material-item").last();
      assert.ok(Number(await lastMaterial.evaluate((element) => getComputedStyle(element).opacity)) < 1, "The last material should wait for the viewport");
      await lastMaterial.scrollIntoViewIfNeeded();
      await page.waitForFunction(() => getComputedStyle(document.querySelector(".material-item:last-child")).opacity === "1");
      const passport = page.locator(".passport-wrap");
      assert.ok(Number(await passport.evaluate((element) => getComputedStyle(element).opacity)) < 1, "The passport should wait for the viewport");
      await passport.scrollIntoViewIfNeeded();
      await page.waitForFunction(() => getComputedStyle(document.querySelector(".passport-wrap")).opacity === "1");
      const businessVisual = page.locator(".business-visual");
      assert.ok(Number(await businessVisual.evaluate((element) => getComputedStyle(element).opacity)) < 1, "The business visual should wait for the viewport");
      await businessVisual.scrollIntoViewIfNeeded();
      await page.waitForFunction(() => getComputedStyle(document.querySelector(".business-visual")).opacity === "1");
    }
  }
  await page.emulateMedia({ reducedMotion: "reduce" });
  await openHome(page);
  assert.equal(await page.locator(".hero-copy").evaluate((element) => getComputedStyle(element).opacity), "1");
  assert.equal(await page.evaluate(() => getComputedStyle(document.documentElement).scrollBehavior), "auto");
  assert.deepEqual(errors, [], "Browser runtime errors");
  console.log("PASS: desktop, 360/390/768px, per-item scroll reveals, journey, material details, saved designs, search, product dialog, trace, B2B demo, collection scroll and reduced motion. No page errors.");
} finally {
  await browser.close();
}
